Traceback (most recent call last):
  File "/home/leron/.local/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/leron/.local/lib/python3.6/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/leron/.local/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/leron/.local/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/leron/.local/lib/python3.6/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/leron/.local/lib/python3.6/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/leron/.local/lib/python3.6/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X = sardine_data['CatchLbs'].values.reshape(-1,1)
Y = sardine_data['Sardine Larvae lbs'].values.reshape(-1,1)
linear_regressor = LinearRegression()
linear_regressor.fit(X, Y)
Y_pred = linear_regressor.predict(X)
Y = np.array(Y).reshape(-1,)
X = np.array(X).reshape(-1,)
rmse = mean_squared_error(Y, Y_pred, squared=False)

fig = px.scatter(sardine_data, x='CatchLbs', y='Sardine Larvae lbs', trendline="ols", title ='Sardine Larvae lbs vs Sardine Catch')
fig.show()
print("Pearson Correlation:", stats.pearsonr(X, Y), "Root Mean Squared Error: ", rmse)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-1fa3fe6d5ca8>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mY[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mY[0m[0;34m)[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mX[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mX[0m[0;34m)[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mrmse[0m [0;34m=[0m [0mmean_squared_error[0m[0;34m([0m[0mY[0m[0;34m,[0m [0mY_pred[0m[0;34m,[0m [0msquared[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;34m[0m[0m
[1;32m     10[0m [0mfig[0m [0;34m=[0m [0mpx[0m[0;34m.[0m[0mscatter[0m[0;34m([0m[0msardine_data[0m[0;34m,[0m [0mx[0m[0;34m=[0m[0;34m'CatchLbs'[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;34m'Sardine Larvae lbs'[0m[0;34m,[0m [0mtrendline[0m[0;34m=[0m[0;34m"ols"[0m[0;34m,[0m [0mtitle[0m [0;34m=[0m[0;34m'Sardine Larvae lbs vs Sardine Catch'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'mean_squared_error' is not defined
NameError: name 'mean_squared_error' is not defined

